### ISSUE TITLE
"libclipper was not found"

### ISSUE THREAD

**Issue by matheousse** [zerefxx/Aegisub-macros#2]
As the title says, aegi doesn't find libclipper when using Stroke functions in Everything Shape. I downloaded/copied everything included in the v1.0.2 archive and the polyclipping files (ZPCP) are present as it is mentionned they are required for this section to work at all.

I may have just done a dumb mistake and haven't noticed, but v1.0.1 worked flawlessly fwiw.

Here is the console output:

```
Lua reported a runtime error:
    File "C:/Users\mathe\AppData\Roaming\Aegisub\automation\autoload\zf.everythingShape.lua", line 519
<anonymous function at lines 329-623>
    File "C:/Users\mathe\AppData\Roaming\Aegisub\automation\include\ZF\2D\clipper.lua", line 161
clipper
    File "C:/Users\mathe\AppData\Roaming\Aegisub\automation\include\ZF\2D\clipper.lua", line 121
__init
    File "<C function>", line -1
?
libclipper was not found

**Comment by zerefxx** [comment]
Did you download the correct architecture version for the Aegisub architecture? If you happen to be on an Aegisub with x86 architecture and downloaded the x64 architecture version of Aegisub-macros the libraries will not load.

If you have done everything correctly and it still doesn't work, I will rebuild the libraries, so just to be sure, answer this issue.

Btw I tested it on several versions of Aegisub, including on different windows platforms and they all worked.

**Comment by zerefxx** [comment]
I tested [AegisubDC](https://github.com/Ristellise/AegisubDC) version [9205](https://github.com/Ristellise/AegisubDC/releases/tag/9215) and really couldn't load the polyclipping library.

The problem has been fixed and is now loaded in releases as version 1.0.2.1.

Do the test and see if the problem is solved for you now and also don't forget to get back to me if everything is ok.

**Comment by matheousse** [comment]
I was using AegisubDC and downloaded x64 package, but using and copying v1.0.2.1 files did fix the issue. Thanks a lot!
